# Generated by Django 6.0.1 on 2026-01-15 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.CharField(blank=True, choices=[('https://i.pinimg.com/736x/64/ba/12/64ba126baf766711499a946cfc2e5af4.jpg', 'Кот оранжевый'), ('https://i.pinimg.com/736x/bd/83/62/bd8362f098ebfa82df5cdbf57e8e6b19.jpg', 'Кот чёрный'), ('https://i.pinimg.com/736x/f4/5a/09/f45a09fecd73e0d72e19a1bc35f38c67.jpg', 'Кот серый'), ('https://i.pinimg.com/736x/a1/2b/3c/a12b3c5f6e8d9f0a1b2c3d4e5f6a7b8c.jpg', 'Кот белый'), ('https://i.pinimg.com/736x/9e/7d/6c/9e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b.jpg', 'Полосатый кот'), ('https://i.pinimg.com/736x/c3/b2/a1/c3b2a1f9e8d7c6b5a4f3e2d1c0b9a8f7.jpg', 'Симпатичный кот'), ('https://i.pinimg.com/736x/d5/e4/f3/d5e4f3c2b1a9f8e7d6c5b4a3f2e1d0c9.jpg', 'Кот спит'), ('https://i.pinimg.com/736x/e6/f5/a4/e6f5a4d3c2b1a0f9e8d7c6b5a4f3e2d1.jpg', 'Молодой кот')], default='https://i.pinimg.com/736x/64/ba/12/64ba126baf766711499a946cfc2e5af4.jpg', max_length=500, null=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
