# Generated by Django 6.0.1 on 2026-01-16 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_pinned_friends',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(blank=True, choices=[('https://i.pinimg.com/736x/93/ce/0f/93ce0faec07582c48a51494374f5f7fb.jpg', 'Черный парень следит'), ('https://i.pinimg.com/736x/bc/77/4e/bc774eadc4eec3a42f68ed3f7eaf34f1.jpg', 'Кот позади взрыв'), ('https://i.pinimg.com/736x/15/28/32/1528324423acc55f1ebde5a74899eb9b.jpg', 'Пепа'), ('https://i.pinimg.com/1200x/f6/f6/cc/f6f6ccb510466e0736f224316e9c5187.jpg', 'я газель'), ('https://i.pinimg.com/736x/82/e5/00/82e50027d447e50b89182f6670240c36.jpg', 'кот на троне'), ('https://i.pinimg.com/736x/13/5c/27/135c27e76a14e2477059cea160c81dac.jpg', 'Симпатичная собака'), ('https://i.pinimg.com/736x/4e/84/5d/4e845dfa164626eb4eea09ddb8e9576e.jpg', 'Симпл'), ('https://i.pinimg.com/736x/b4/18/33/b418335314fbf4be4aa3b840eda9c840.jpg', 'вьетнам кот')], default='https://i.pinimg.com/736x/93/ce/0f/93ce0faec07582c48a51494374f5f7fb.jpg', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='PinnedFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_friends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pinned_at'],
                'unique_together': {('user', 'friend')},
            },
        ),
    ]
